name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t ghcr.io/Mercy1322/stardrop/student-node-395:latest ./node/
